kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traffic-claim-enforcer-configurator
  namespace: {{ .Release.Namespace }}
  labels:
    app: traffic-claim-enforcer
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: traffic-claim-enforcer-configurator-service-account
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: traffic-claim-enforcer-configurator
  apiGroup: rbac.authorization.k8s.io
