apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: traffic-claim-enforcer-configurator
  labels:
    app: traffic-claim-enforcer
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["services"]
  resourceNames: ["traffic-claim-enforcer-webhook"]
  verbs: ["get"]
- apiGroups: ["apps", "extensions"]
  resources: ["deployments"]
  resourceNames: ["traffic-claim-enforcer-webhook"]
  verbs: ["get", "patch"]
