apiVersion: v1
kind: ConfigMap
metadata:
  name: aspen-mesh-secure-ingress-configurator
  namespace: {{ .Release.Namespace }}
  labels:
    app: aspen-mesh-secure-ingress
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  run.sh: |-
{{ .Files.Get "create-webhook-certs.sh" | indent 4 }}
  webhook.yaml: |-
    apiVersion: admissionregistration.k8s.io/v1beta1
    kind: ValidatingWebhookConfiguration
    metadata:
      name: aspen-mesh-secure-ingress
      namespace: {{ .Release.Namespace }}
      labels:
        app: aspen-mesh-secure-ingress
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
      ownerReferences:
      - apiVersion: v1
        blockOwnerDeletion: false
        controller: false
        kind: Service
        name: aspen-mesh-secure-ingress
        uid: __UID__
    webhooks:
    - name: secure-ingress.aspenmesh.io
      clientConfig:
        service:
          name: aspen-mesh-secure-ingress
          namespace: {{ .Release.Namespace }}
          path: "/validate"
        caBundle: __CABUNDLE__
      rules:
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: ["policy.aspenmesh.io"]
        apiVersions: ["v1alpha1"]
        resources:
        - applications
        - secureingresses
        # TODO specify the scope once Kubernetes 1.14 is the minimum supported
        # version. Scoping is not supported in versions prior to 1.14.
        # scope: "Namespaced"
      failurePolicy: Fail
