{{- if .Values.alertmanager.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: aspen-mesh-alertmanager
  namespace: {{ .Release.Namespace }}
  labels:
    app: aspen-mesh-alertmanager
    chart: {{ template "aspen-mesh-metrics-collector.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  alertmanager.yml: |
    global: {}

    receivers:
    - name: default-receiver

    route:
      group_wait: 10s
      group_interval: 5m
      receiver: default-receiver
      repeat_interval: 3h
{{- end }}
