{{- if and .Values.collector.enabled .Values.collector.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
{{- range .Values.global.imagePullSecrets }}
- name: {{ . }}
{{- end }}
metadata:
  name: {{ template "jaeger.collector.serviceAccountName" . }}
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
    app.kubernetes.io/component: collector
{{- end -}}
