apiVersion: v1
kind: Service
metadata:
  name: aspen-mesh-alertmanager
  namespace: {{ .Release.Namespace }}
  annotations:
    prometheus.io/scrape: 'true'
    {{- range $key, $val := .Values.alertmanager.service.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  labels:
    app: aspen-mesh-alertmanager
    chart: {{ template "aspen-mesh-metrics-collector.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: aspen-mesh-alertmanager
  ports:
  - name: http-aspen-mesh-alertmanager
    protocol: TCP
    port: {{ .Values.alertmanager.service.servicePort }}
    targetPort: 9093
