global:
  imagePullSecrets:
  - aspen-mesh-pull-secret
  hub: quay.io/aspenmesh/releases
  controlPlaneSecurityEnabled: true

  proxy:
    accessLogFile: "/dev/stdout"

  outboundTrafficPolicy:
    mode: REGISTRY_ONLY

  tracer:
    zipkin:
      # address is the Host:Port for reporting trace data in zipkin format. If
      # not specified, will default to zipkin service (port 9411) in the same
      # namespace as the other istio components.
      address: ""

  certificateCustomFields: false

galley:
  podAntiAffinityLabelSelector:
  - key: app
    operator: In
    values: galley
    topologyKey: "kubernetes.io/hostname"

  replicaCount: 2

gateways:
  istio-ingressgateway:
    autoscaleMin: 2
    podAntiAffinityLabelSelector:
    - key: app
      operator: In
      values: istio-ingressgateway
      topologyKey: "kubernetes.io/hostname"
    sds:
      enabled: true
  istio-egressgateway:
    enabled: false
    autoscaleMin: 2
    podAntiAffinityLabelSelector:
    - key: app
      operator: In
      values: istio-egressgateway
      topologyKey: "kubernetes.io/hostname"

mixer:
  policy:
    autoscaleMin: 2
    autoscaleMax: 3
    podAntiAffinityLabelSelector:
    - key: app
      operator: In
      values: policy
      topologyKey: "kubernetes.io/hostname"
  telemetry:
    autoscaleMin: 2
    autoscaleMax: 3
    podAntiAffinityLabelSelector:
    - key: app
      operator: In
      values: telemetry
      topologyKey: "kubernetes.io/hostname"

pilot:
  # Aspen Mesh has decided to disable this experimental feature until
  # both outbound and inbound protocol sniffing is merged and is
  # stable
  enableProtocolSniffingForOutbound: false
  enableProtocolSniffingForInbound: false
  autoscaleMin: 2
  podAntiAffinityLabelSelector:
  - key: app
    operator: In
    values: pilot
    topologyKey: "kubernetes.io/hostname"

security:
  replicaCount: 2
  podAntiAffinityLabelSelector:
  - key: istio
    operator: In
    values: citadel
    topologyKey: "kubernetes.io/hostname"

aspen-mesh-controlplane:
  enabled: true
  image: controlplane-1.5.10-am2
  modelruntimeImage: modelruntime-1.5.10-am2

  imagePullSecrets:
  - aspenmesh-kubernetes-pull-secret

  replicaCount: 2

  clusterId: demo

  userAuth:
    # "type" can be none, jwt or oauthOpenshift.  Configure details for your chosen type below, others are ignored.
    type: jwt
    jwt:
      # jwks must provide a valid JWKs endpoint.
      # Required: Valid endpoint to retrieve the JWKS from
      jwks:
      # redirectUrl must provide an unauthenticated redirect URL.
      # Required: URL to redirect unauthenticated users to (to start the authentication workflow)
      redirectUrl:
      # claims can be added here to require claims be present in the JWT
      # (e.g.: `claims: aud=aspenmesh:io,role=k8s:admin`).
    oauthOpenshift:
      # Optional: Where the Aspen Mesh dashboard will be exposed.  If provided we will configure
      # an OpenShift route and set up redirect URIs.
      host:

  openshiftOauthProxy:
    image: openshift-oauth-proxy-1.5.10-am2

  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "100m"
  modelRuntimeResources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "100m"

aspen-mesh-dashboard:
  enabled: true
  image: dashboard-1.5.10-am2
  replicaCount: 2

aspen-mesh-secure-ingress:
  enabled: true
  image: secure-ingress-1.5.10-am2
  # Email to use for Let's Encrypt registration (used for certificate expiry notices)
  # Leave blank ("") if you wish to manage your own TLS certificates.
  lets-encrypt-email: ""
  resources: {}
  externalDnsAnnotation: "policy.aspenmesh.io/externaldns"
  externalDnsEnabled: false

aspen-mesh-metrics-collector:
  serviceImage: metrics-collector-service-1.5.10-am2
  server:
    serviceResources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "512Mi"
        cpu: "500m"
  alertmanagerImage: alertmanager-1.5.10-am2
  configmapReloadImage: configmap-reloader-1.5.10-am2

traffic-claim-enforcer:
  enabled: true
  image: traffic-claim-enforcer-1.5.10-am2
  resources: {}

istio_cni:
  # To enable CNI-based installations, set this to true and follow additional
  # CNI installation instructions to install the istio-cni Helm chart. Also
  # un-comment out the additional settings for sidecarInjectorWebhook for
  # CNI-based installations to work.
  enabled: false

sidecarInjectorWebhook:
  replicaCount: 2
  podAntiAffinityLabelSelector:
  - key: app
    operator: In
    values: sidecarInjectorWebhook
    topologyKey: "kubernetes.io/hostname"
  #
  # When CNI is enabled, "injectedAnnotations" needs to set
  # "k8s.v1.cni.cncf.io/networks: istio-cni"
  #
  # injectedAnnotations:
  #   k8s.v1.cni.cncf.io/networks: istio-cni
  injectedAnnotations: {}

prometheus:
  enabled: false

cassandra:
  enabled: false
  fullnameOverride: aspen-mesh-cassandra

cert-manager:
  enabled: true
  fullnameOverride: aspen-mesh-cert-manager

external-dns:
  enabled: true
  fullnameOverride: aspen-mesh-external-dns

  annotationFilter: "policy.aspenmesh.io/externaldns=true"
  policy: sync
  provider: aws
  sources: ["istio-gateway"]
  txtOwnerId: aspen-mesh-secure-ingress
