---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: f5gc-gnbsim-2-n1n2
spec:
  config: |
    { 
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "ens6",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "172.16.10.11/24",
            "gateway": "172.16.10.1"
          }
        ]
      }
    }

---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: f5gc-gnbsim-2-n3
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "ens6",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "192.168.10.11/24",
            "gateway": "192.168.10.1"
          }
        ]
      }
    }
