---
apiVersion: v1
kind: ConfigMap
metadata:
  name: f5gc-ausf-config
data:
  ausfcfg.conf: |
    info:
      version: 1.0.0
      description: AUSF initial local configuration
    
    configuration:
      sbi: # Service-based interface information
        scheme: http              # the protocol for sbi (http or https)
        registerIPv4: f5gc-ausf   # IP/DNS used to register to NRF
        bindingIPv4: 0.0.0.0      # IP used to bind the service
        port: 29509               # Port used to bind the service
      serviceNameList: # the SBI services provided by this AUSF, refer to TS 29.509
        - nausf-auth # Nausf_UEAuthentication service
      nrfUri: http://f5gc-nrf:29510 # a valid URI of NRF
      plmnSupportList: # the PLMNs (Public Land Mobile Network) list supported by this AUSF
        - mcc: 208  # Mobile Country Code (3 digits string, digit: 0~9)
          mnc: 93   # Mobile Network Code (2 or 3 digits string, digit: 0~9)
        - mcc: 123  # Mobile Country Code (3 digits string, digit: 0~9)
          mnc: 45   # Mobile Network Code (2 or 3 digits string, digit: 0~9)
      groupId: ausfGroup001 # ID for the group of the AUSF

    # the kind of log output
      # debugLevel: trace, debug, info, warn, error, fatal, panic
      # ReportCaller: true or false
    logger:
      AUSF:
        debugLevel: trace
        ReportCaller: true
      PathUtil:
        debugLevel: info
        ReportCaller: false
      OpenApi:
        debugLevel: debug
        ReportCaller: true
