apiVersion: v1
kind: ConfigMap
metadata:
  name: f5gc-ausf-config
data:
  ausfcfg.conf: |
    info:
      version: 1.0.0
      description: AUSF initial local configuration
    
    configuration:
      sbi:
        scheme: http
        registerIPv4: f5gc-ausf     # Can also be a kubernetes service IP or domain name.
        bindingIPv4: 0.0.0.0      # Can also be an ENV.
        port: 29509
      serviceNameList:
        - nausf-auth
      nrfUri: http://f5gc-nrf:29510
      plmnSupportList:
        - mcc: 208
          mnc: 93
        - mcc: 123
          mnc: 45
      groupId: ausfGroup001  

    db_uri: mongodb://f5gc-mongodb:27017/free5GC

    # the kind of log output
      # debugLevel: how detailed to output, value: trace, debug, info, warn, error, fatal, panic
      # ReportCaller: enable the caller report or not, value: true or false
    logger:
      AUSF:
        debugLevel: debug
        ReportCaller: false
      PathUtil:
        debugLevel: info
        ReportCaller: false
      OpenApi:
        debugLevel: info
        ReportCaller: false
