---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: f5gc-smf-2-n4
spec:
  config: |
    { 
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "ens6",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "172.16.30.21/24",
            "gateway": "172.16.30.1"
          }
        ]
      }
    }
