---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dbg-mongo-express
  name: dbg-mongo-express
spec:
  #type: NodePort
  ports:
  - name: http-mongo-express
    port: 8081
    protocol: TCP
    targetPort: 8081
    #nodePort: 30501
  selector:
    app: dbg-mongo-express
---
