apiVersion: policy.aspenmesh.io/v1alpha1
kind: Application
metadata:
  name: dbg-mongo-express
  namespace: f5gc
spec:
  inbound:
    ports:
      - number: 8081
        protocol: HTTP
        paths:
          - expose:
              public: true
              jwtSecured: false
            uri:
              prefix: /
---
apiVersion: policy.aspenmesh.io/v1alpha1
kind: SecureIngress
metadata:
  name: mongoexpress
spec:
  domainName: "mongo-express.udf-demo.org, 10.1.1.5, 10.1.1.6, 10.1.1.7, 10.1.1.8, 10.1.1.9"
  exposedApplications:
    - applicationReference:
        name: dbg-mongo-express
        namespace: f5gc
      serviceReference:
        name: dbg-mongo-express
        namespace: f5gc
---
