apiVersion: v1
kind: Service
metadata:
  name: aspen-mesh-metrics-collector
  namespace: {{ .Release.Namespace }}
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: aspen-mesh-metrics-collector
    chart: {{ template "aspen-mesh-metrics-collector.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: aspen-mesh-metrics-collector
  ports:
  - name: http-aspen-mesh-metrics-collector
    port: {{ .Values.server.service.servicePort }}
    protocol: TCP
    targetPort: 9090
