apiVersion: v1
kind: Service
metadata:
  name: aspen-mesh-packet-inspector
  namespace: {{ .Release.Namespace }}
  labels:
    istio: aspen-mesh-packet-inspector
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
  - name: grpc
    port: 20000
    protocol: TCP
    nodePort: {{ .Values.nodePort }}
  selector:
    istio: aspen-mesh-packet-inspector
