image: # Override with appropriate image and tag.

enabled: false

nodePort: 31672

analysis:
  address: aspen-mesh-analysis-emulator.analysis-emulator:21000
  certPath: /etc/analysis/certs
  caCert: root-cert.pem
  clientCert: cert-chain.pem
  clientKey: key.pem
  maxConnections: 1
  maxConcurrentMessages: 5
  # reconnect time to Analysis service to avoid un-balanced load
  # value in the unit of minutes
  reconnectTime: 5
  maxErrorRetries: 3
  verbose: false


tapfilterBufferSize: 5kb
tapfilterTimeout: 1000ms
macAddress: 00:00:00:00:00:00

runOnMaster: false

certPath: /etc/packet-inspector/certs
tlsRootCert: root-cert.pem
tlsCert: cert-chain.pem
tlsKey: key.pem

daemonSetBufferMemoryPercent: 50

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  # this limit is used to calculate the maximum buffer size
  # for the daemon set to keep messages before starting to drop
  # older messages. It's important that this number can be
  # adjusted based on the usage. However, it's highly
  # recommended that DO NOT remove the limit. If this limit
  # is removed, the node's memory limit will be used to
  # calculate the buffer size to be used. WARNING: if calculation
  # is based on node's memory (due to removal of the limits),
  # the daemon set will use a very large buffer size and possibly take
  # up too much memory from the node.
  limits:
    memory: "128Mi"
    cpu: "100m"
