kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traffic-claim-enforcer
  labels:
    app: traffic-claim-enforcer
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: traffic-claim-enforcer-service-account
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: traffic-claim-enforcer
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traffic-claim-enforcer-configurator
subjects:
- kind: ServiceAccount
  name: traffic-claim-enforcer-configurator-service-account
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: traffic-claim-enforcer-configurator
  apiGroup: rbac.authorization.k8s.io
