---
apiVersion: v1
kind: ConfigMap
metadata:
  name: f5gc-udr-config
data:
  udrcfg.conf: |
    info:
      version: 1.0.0
      description: UDR initial local configuration

    configuration:
      sbi: # Service-based interface information
        scheme: http              # the protocol for sbi (http or https)
        registerIPv4: f5gc-udr    # IP used to register to NRF
        bindingIPv4: 0.0.0.0      # IP used to bind the service
        port: 29504               # port used to bind the service
      mongodb:
        name: free5gc                       # Database name in MongoDB
        url: mongodb://f5gc-mongodb:27017   # URL of MongoDB
      nrfUri: http://f5gc-nrf:29510         # a valid URI of NRF

    # the kind of log output
      # debugLevel: trace, debug, info, warn, error, fatal, panic
      # ReportCaller: true or false
    logger:
      UDR:
        debugLevel: trace
        ReportCaller: true
      MongoDBLibrary:
        debugLevel: trace
        ReportCaller: true
      PathUtil:
        debugLevel: info
        ReportCaller: false
      OpenApi:
        debugLevel: debug
        ReportCaller: true
