apiVersion: v1
kind: Service
metadata:
  labels:
    app: f5gc-udr
  name: f5gc-udr
spec:
  type: ClusterIP
  ports:
  - name: f5gc-udr
    port: 29504
    protocol: TCP
    targetPort: 29504
  selector:
    app: f5gc-udr
