---
apiVersion: v1
kind: ConfigMap
metadata:
  name: f5gc-amf-config
data:
  amfcfg.conf: |
    info:
      version: 1.0.0
      description: AMF initial local configuration
    
    configuration:
      amfName: AMF        # the name of this AMF
      ngapIpList:         # the IP list of N2 interfaces on this AMF
        - 172.16.10.20    # assigned to a second network interface with multus
      sbi:                # Service-based interface information
        scheme: http            # the protocol for sbi (http or https)
        registerIPv4: f5gc-amf  # IP/DNS used to register to NRF
        bindingIPv4: 0.0.0.0    # IP used to bind the service
        port: 29518             # port used to bind the service
      serviceNameList:    # the SBI services provided by this AMF, refer to TS 29.518
        - namf-comm # Namf_Communication service
        - namf-evts # Namf_EventExposure service
        - namf-mt   # Namf_MT service
        - namf-loc  # Namf_Location service
        - namf-oam  # OAM service
      servedGuamiList:    # Guami (Globally Unique AMF ID) list supported by this AMF
                          # <GUAMI> = <MCC><MNC><AMF ID>
        - plmnId:         # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>
            mcc: 208      # Mobile Country Code (3 digits string, digit: 0~9)
            mnc: 93       # Mobile Network Code (2 or 3 digits string, digit: 0~9)
          amfId: cafe00   # AMF identifier (3 bytes hex string, range: 000000~FFFFFF)
      supportTaiList:     # the TAI (Tracking Area Identifier) list supported by this AMF
        - plmnId:         # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>
            mcc: 208      # Mobile Country Code (3 digits string, digit: 0~9)
            mnc: 93       # Mobile Network Code (2 or 3 digits string, digit: 0~9)
          tac: 1          # Tracking Area Code (uinteger, range: 0~16777215)
      plmnSupportList:    # the PLMNs (Public land mobile network) list supported by this AMF
        - plmnId:         # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>
            mcc: 208      # Mobile Country Code (3 digits string, digit: 0~9)
            mnc: 93       # Mobile Network Code (2 or 3 digits string, digit: 0~9)
          snssaiList:     # S-NSSAI (Single Network Slice Selection Assistance Information) list supported by this AMF
            - sst: 1      # Slice/Service Type (uinteger, range: 0~255)
              sd: 010203  # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
            - sst: 1      # Slice/Service Type (uinteger, range: 0~255)
              sd: 112233  # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
      supportDnnList:     # the DNN (Data Network Name) list supported by this AMF
        - internet
      nrfUri: http://f5gc-nrf:29510   # a valid URI of NRF
      security:           # NAS security parameters
        integrityOrder:   # the priority of integrity algorithms
          - NIA2
          - NIA0
        cipheringOrder:   # the priority of ciphering algorithms
          - NEA2
          - NEA0
      networkName:        # the name of this core network
        full: free5GC
        short: free
      t3502: 720          # timer value (seconds) at UE side
      t3512: 3600         # timer value (seconds) at UE side
      non3gppDeregistrationTimer: 1000  # timer value (seconds) at UE side
      t3513:             # retransmission timer for paging message
        enable: true     # true or false
        expireTime: 6s   # default is 6 seconds
        maxRetryTimes: 4 # the max number of retransmission
      t3522:    # retransmission timer for NAS Deregistration Request message
        enable: true     # true or false
        expireTime: 6s   # default is 6 seconds
        maxRetryTimes: 4 # the max number of retransmission
      t3550:    # retransmission timer for NAS Registration Accept message
        enable: true     # true or false
        expireTime: 6s   # default is 6 seconds
        maxRetryTimes: 4 # the max number of retransmission
      t3560:    # retransmission timer for NAS Authentication Request/Security Mode Command message
        enable: true     # true or false
        expireTime: 6s   # default is 6 seconds
        maxRetryTimes: 4 # the max number of retransmission
      t3565:    # retransmission timer for NAS Notification message
        enable: true     # true or false
        expireTime: 6s   # default is 6 seconds
        maxRetryTimes: 4 # the max number of retransmission
    
    # the kind of log output
      # debugLevel: trace, debug, info, warn, error, fatal, panic
      # ReportCaller: true or false
    logger:
      AMF:
        debugLevel: trace
        ReportCaller: true
      NAS:
        debugLevel: info
        ReportCaller: false
      FSM:
        debugLevel: info
        ReportCaller: false
      NGAP:
        debugLevel: info
        ReportCaller: false
      Aper:
        debugLevel: info
        ReportCaller: false
      PathUtil:
        debugLevel: info
        ReportCaller: false
      OpenApi:
        debugLevel: debug
        ReportCaller: true
