apiVersion: v1
kind: ConfigMap
metadata:
  name: f5gc-amf-config
data:
  amfcfg.conf: |
    info:
      version: 1.0.0
      description: AMF initial local configuration
    
    configuration:
      amfName: AMF
      ngapIpList:
        - 0.0.0.0                 # assigned to a second network interface
      sbi:
        scheme: http
        registerIPv4: f5gc-amf         # Can also be a kubernetes service IP or domain name.
        bindingIPv4: 0.0.0.0           # Can also be an ENV.
        port: 29518
      serviceNameList:
        - namf-comm
        - namf-evts
        - namf-mt
        - namf-loc
        - namf-oam
      servedGuamiList:
        - plmnId:
            mcc: 208
            mnc: 93
          amfId: cafe00
      supportTaiList:
        - plmnId:
            mcc: 208
            mnc: 93
          tac: 1
      plmnSupportList:
        - plmnId:
            mcc: 208
            mnc: 93
          snssaiList:
            - sst: 1
              sd: 010203
            - sst: 1
              sd: 112233
      supportDnnList:
        - internet
      nrfUri: http://f5gc-nrf:29510
      security:
        integrityOrder:
          - NIA2
          - NIA0
        cipheringOrder:
          - NEA2
          - NEA0
      networkName:
        full: free5GC
        short: free
      t3502: 720
      t3512: 3600
      non3gppDeregistrationTimer: 1000

    db_uri: mongodb://f5gc-mongodb:27017/free5GC
    
    # the kind of log output
      # debugLevel: how detailed to output, value: trace, debug, info, warn, error, fatal, panic
      # ReportCaller: enable the caller report or not, value: true or false
    logger:
      AMF:
        debugLevel: debug
        ReportCaller: false
      NAS:
        debugLevel: info
        ReportCaller: false
      FSM:
        debugLevel: info
        ReportCaller: false
      NGAP:
        debugLevel: info
        ReportCaller: false
      Aper:
        debugLevel: info
        ReportCaller: false
      PathUtil:
        debugLevel: info
        ReportCaller: false
      OpenApi:
        debugLevel: info
        ReportCaller: false
