global:
  # Specify pod scheduling arch(amd64, ppc64le, s390x) and weight as follows:
  #   0 - Never scheduled
  #   1 - Least preferred
  #   2 - No preference
  #   3 - Most preferred
  # Used by node affinity template. Leaving as amd64 only for now as no AM images
  # are cross-compiled.
  arch:
    amd64: 2
