apiVersion: apps/v1
kind: Deployment
metadata:
  name: analysis-emulator
  namespace: {{ .Release.Namespace }}
  labels:
    app: analysis-emulator
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analysis-emulator
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: analysis-emulator
    spec:
      serviceAccountName: aspen-mesh-packet-inspector-analysis
      containers:
      - image: {{ template "aspen-mesh-analysis-emulator.imagePath" . }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        name: aspen-mesh-analysis-emulator
        command:
        - "analysis-emulator"
        - "--listen-http=0.0.0.0:21000"
        - "--listen-admin=0.0.0.0:21001"
        - "--production-logging"
        - "--tls-cert-file={{ .Values.analysis.certPath }}/cert-chain.pem"
        - "--tls-key-file={{ .Values.analysis.certPath }}/key.pem"
        - "--processing-delay={{ .Values.analysis.processingDelay }}"
        {{- if eq .Values.analysis.mode "benchmark" }}
        - "--file-no-op"
        - "--track-unique-requests"
        {{- end }}
        ports:
        - containerPort: 21000
          protocol: TCP
          name: http
        volumeMounts:
        - name: analysis-certs
          mountPath: {{ .Values.analysis.certPath }}
          readOnly: true
      volumes:
      - name: analysis-certs
        secret:
          secretName: istio.aspen-mesh-packet-inspector-analysis
