---
apiVersion: v1
kind: ConfigMap
metadata:
  name: f5gc-udm-config
data:
  udmcfg.conf: |
    info:
      version: 1.0.0
      description: UDM initial local configuration
    
    configuration:
      serviceNameList: # the SBI services provided by this UDM, refer to TS 29.503
        - nudm-sdm    # Nudm_SubscriberDataManagement service
        - nudm-uecm   # Nudm_UEContextManagement service
        - nudm-ueau   # Nudm_UEAuthenticationManagement service
        - nudm-ee     # Nudm_EventExposureManagement service
        - nudm-pp     # Nudm_ParameterProvisionDataManagement service
      sbi: # Service-based interface information
        scheme: http              # the protocol for sbi (http or https)
        registerIPv4: f5gc-udm    # IP/DNS used to register to NRF
        bindingIPv4: 0.0.0.0      # IP used to bind the service
        port: 29503               # Port used to bind the service
        tls:
          log: free5gc/udmsslkey.log # UDM keylog
          pem: free5gc/support/TLS/udm.pem # UDM TLS Certificate
          key: free5gc/support/TLS/udm.key # UDM TLS Private key
      nrfUri: http://f5gc-nrf:29510 # a valid URI of NRF
    
      # test data set from TS33501-f60 Annex C.4
      keys:
        udmProfileAHNPublicKey: 5a8d38864820197c3394b92613b20b91633cbd897119273bf8e4a6f4eec0a650
        udmProfileAHNPrivateKey: c53c22208b61860b06c62e5406a7b330c2b577aa5558981510d128247d38bd1d
        udmProfileBHNPublicKey: 0472DA71976234CE833A6907425867B82E074D44EF907DFB4B3E21C1C2256EBCD15A7DED52FCBB097A4ED250E036C7B9C8C7004C4EEDC4F068CD7BF8D3F900E3B4
        udmProfileBHNPrivateKey: F1AB1074477EBCC7F554EA1C5FC368B1616730155E0041AC447D6301975FECDA

    # the kind of log output
      # debugLevel: trace, debug, info, warn, error, fatal, panic
      # ReportCaller: true or false
    logger:
      UDM:
        debugLevel: trace
        ReportCaller: true
      OpenApi:
        debugLevel: debug
        ReportCaller: true
      PathUtil:
        debugLevel: info
        ReportCaller: false
