apiVersion: v1
kind: Service
metadata:
  labels:
    app: f5gc-udm
  name: f5gc-udm
spec:
  type: ClusterIP
  ports:
  - name: f5gc-udm
    port: 29503
    protocol: TCP
    targetPort: 29503
  selector:
    app: f5gc-udm
