apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: analysis-emulator
    meta.helm.sh/release-namespace: analysis-emulator
  labels:
    app: analysis-emulator
    app.kubernetes.io/managed-by: Helm
    chart: analysis-emulator-0.1.0
    heritage: Helm
    release: analysis-emulator
  name: analysis-emulator
  namespace: analysis-emulator
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: analysis-emulator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        app: analysis-emulator
    spec:
      containers:
      - command:
        - analysis-emulator
        - --listen-http=0.0.0.0:21000
        - --production-logging
        image: quay.io/aspenmesh/carrier-grade-releases:analysis-emulator-1.6.14-am4
        imagePullPolicy: Always
        name: aspen-mesh-analysis-emulator
        ports:
        - containerPort: 21000
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/analysis/certs
          name: analysis-certs
          readOnly: true
        - mountPath: /tmp
          name: capture-folder
          readOnly: false
      - image: webshark/webshark:devel
        name: webshark
        ports:
        - containerPort: 80
          name: webshark
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /caps
          name: capture-folder
          readOnly: true
      - image: boeboe/wetty-bson-decode:1.0.0
        name: wetty-bson
        ports:
        - containerPort: 3000
          name: wetty-bson
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: capture-folder
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: aspen-mesh-packet-inspector-analysis
      serviceAccountName: aspen-mesh-packet-inspector-analysis
      terminationGracePeriodSeconds: 30
      volumes:
      - name: analysis-certs
        secret:
          defaultMode: 420
          secretName: istio.aspen-mesh-packet-inspector-analysis
      - name: capture-folder
        emptyDir: {}
