apiVersion: v1
kind: Service
metadata:
  labels:
    app: aspen-mesh-analysis-emulator
    app.kubernetes.io/managed-by: Helm
    chart: analysis-emulator-0.1.0
    heritage: Helm
    release: analysis-emulator
  name: webshark-np
  namespace: analysis-emulator
spec:
  ports:
  - name: webshark
    port: 30008
    protocol: TCP
    targetPort: webshark
    nodePort: 30008
  selector:
    app: analysis-emulator
  sessionAffinity: None
  type: NodePort
