apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: grafana-np
  name: grafana-np
  namespace: istio-system
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30002
  selector:
    app.kubernetes.io/name: grafana
  sessionAffinity: None
  type: NodePort
