apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana-np
    release: istiod
  name: grafana
  namespace: istio-system
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30002
  selector:
    app: grafana
  sessionAffinity: None
  type: NodePort
