apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: query
    app.kubernetes.io/instance: istiod
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/version: 1.16.0
  name: aspen-mesh-jaeger-query-np
  namespace: istio-system
spec:
  ports:
  - name: query
    port: 80
    protocol: TCP
    targetPort: query
    nodePort: 30004
  selector:
    app.kubernetes.io/component: query
    app.kubernetes.io/instance: istiod
    app.kubernetes.io/name: jaeger
  sessionAffinity: None
  type: NodePort
