apiVersion: v1
kind: Service
metadata:
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    release: istio-ingress
  name: istio-ingressgateway-np
  namespace: istio-system
spec:
  ports:
  - name: status-port
    port: 15021
    protocol: TCP
    targetPort: 15021
    nodePort: 31000
  - name: http2
    port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 31001
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
    nodePort: 31002
  - name: tls
    port: 15443
    protocol: TCP
    targetPort: 15443
    nodePort: 31003
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  sessionAffinity: None
  type: NodePort
