apiVersion: v1
kind: Service
metadata:
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    release: istio-ingress
  name: istio-ingressgateway
  namespace: istio-system
spec:
  ports:
  - name: status-port
    port: 15021
    protocol: TCP
    targetPort: 15021
    nodePort: 18080
  - name: http2
    port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 10080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
    nodePort: 10443
  - name: tls
    port: 15443
    protocol: TCP
    targetPort: 15443
    nodePort: 18443
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  sessionAffinity: None
  type: NodePort
