{{- if eq .Values.userAuth.type "oauthOpenshift" }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: aspen-mesh-oauth-proxy
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: aspen-mesh-oauth-proxy
type: Opaque
data:
  cookie-secret: {{ randAlphaNum 128 | b64enc | quote }}
{{- end }}
