apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aspen-mesh-controlplane-configurator
  namespace: {{ .Release.Namespace }}
  labels:
    app: aspen-mesh-controlplane
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["services"]
  resourceNames: ["aspen-mesh-controlplane"]
  verbs: ["get"]
- apiGroups: ["apps", "extensions"]
  resources: ["deployments"]
  resourceNames: ["aspen-mesh-controlplane"]
  verbs: ["get", "patch"]
