{{- if and (eq .Values.userAuth.type "oauthOpenshift") (.Values.userAuth.oauthOpenshift.host) }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
    name: aspen-mesh-controlplane
    namespace: istio-system
spec:
  host: {{ .Values.userAuth.oauthOpenshift.host }}
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: aspen-mesh-controlplane
{{- end }}
