---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: f5gc-upf-2
  labels:
    app: f5gc-upf-2
    sliceidx: f2755a68-e24a-4112-8931-ffad4bafa0e2
  annotations:
    free5gc.org/nssi-id: '27394d25-dbf5-428e-8fc3-f5b2add67115'
    free5gc.org/nsi-ids: '[
        { "id": "4e6db941-47d6-4fce-9c71-f7eb35a75d03" },
    ]'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f5gc-upf-2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: f5gc-upf-2
      annotations:
        k8s.v1.cni.cncf.io/networks: f5gc-upf-2-n3, f5gc-upf-2-n4, f5gc-upf-2-n6
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: f5gc-upf
          image: boeboe/f5gc-upf:v3.0.5-dbg
          imagePullPolicy: Always
          securityContext:
            privileged: false
            capabilities:
              add: ["NET_ADMIN", "NET_RAW", "NET_BIND_SERVICE", "SYS_TIME"]
          volumeMounts:
            - name: f5gc-upf-config
              mountPath: /free5gc/config
            - mountPath: /dev/net/tun
              name: tun-devdir
          ports:
            - containerPort: 2152
              name: if-n3
              protocol: UDP
            - containerPort: 8805
              name: if-n4
              protocol: UDP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: f5gc-upf-sa
      terminationGracePeriodSeconds: 30
      volumes:
        - name: f5gc-upf-config
          configMap:
            name: f5gc-upf-config-2
        - name: tun-devdir
          hostPath:
            path: /dev/net/tun
