kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: aspen-mesh-metrics-collector
  labels:
    app: aspen-mesh-metrics-collector
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: aspen-mesh-metrics-collector
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: aspen-mesh-metrics-collector-istio-system
  apiGroup: rbac.authorization.k8s.io

