apiVersion: v1
appVersion: 0.5.18
description: ExternalDNS is a Kubernetes addon that configures public DNS servers
  with information about exposed Kubernetes services to make them discoverable.
engine: gotpl
home: https://github.com/kubernetes-incubator/external-dns
icon: https://bitnami.com/assets/stacks/external-dns/img/external-dns-stack-110x117.png
keywords:
- external-dns
- network
- dns
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: external-dns
sources:
- https://github.com/kubernetes-incubator/external-dns
- https://github.com/bitnami/bitnami-docker-external-dns
version: 2.16.1
