apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
{{- range .Values.global.imagePullSecrets }}
- name: {{ . }}
{{- end }}
metadata:
  name: istio-multi
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
{{- range .Values.global.imagePullSecrets }}
- name: {{ . }}
{{- end }}
metadata:
  name: istio-reader-service-account
  namespace: {{ .Release.Namespace }}
