{{- if and .Values.hotrod.enabled .Values.hotrod.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
{{- range .Values.global.imagePullSecrets }}
- name: {{ . }}
{{- end }}
metadata:
  name: {{ template "jaeger.hotrod.serviceAccountName" . }}
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
    app.kubernetes.io/component: hotrod
{{- end -}}
