apiVersion: v1
name: mixer
version: 1.5.10-am2
appVersion: 1.5.10-am2
tillerVersion: ">=2.7.2"
description: Helm chart for mixer deployment
keywords:
  - istio
  - mixer
sources:
  - http://github.com/istio/istio
engine: gotpl
icon: https://istio.io/favicons/android-192x192.png
