global:
  imagePullSecrets:
  - aspen-mesh-pull-secret
  hub: quay.io/aspenmesh/carrier-grade-releases

  imagePullPolicy: Always

image: analysis-emulator-1.9.8-am1

analysis:
  certPath: /etc/analysis/certs
  # mode is either `normal` or `benchmark`. `benchmark` does not write capture
  # files and tracks unique requests
  mode: normal
  # processingDelay is a duration to wait after the emulator receives a file.
  # Used to simulate processing time.
  processingDelay: 0ms
