apiVersion: v1
kind: Service
metadata:
  labels:
    app: f5gc-nssf
  name: f5gc-nssf
spec:
  type: ClusterIP
  ports:
  - name: f5gc-nssf
    port: 29531
    protocol: TCP
    targetPort: 29531
  selector:
    app: f5gc-nssf
