{{- if and (.Files.Glob "files/*") (not .Values.initDBConfigMap) }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "cassandra.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "cassandra.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ (.Files.Glob "files/*").AsConfig | indent 2 }}
{{- end }}
