---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: f5gc-mongodb
  name: f5gc-mongodb
spec:
  type: ClusterIP
  ports:
  - name: f5gc-mongodb
    port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    app: f5gc-mongodb
