image: # Override with appropriate image and tag.

modelruntimeImage: # Override with appropriate image and tag.

replicaCount: 2

clusterId: default

userAuth:
  type: jwt
  jwt:
    jwks: # Must provide a valid JWKs endpoint.
    redirectUrl: # Must provide an unauthenticated redirect URL.
#      claims:
  oauthOpenshift:
    host:

prometheusUrl:

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "160Mi"
    cpu: "100m"
modelRuntimeResources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "100m"

global:
  # Specify pod scheduling arch(amd64, ppc64le, s390x) and weight as follows:
  #   0 - Never scheduled
  #   1 - Least preferred
  #   2 - No preference
  #   3 - Most preferred
  # Used by node affinity template. Leaving as amd64 only for now as no AM images
  # are cross-compiled.
  arch:
    amd64: 2
