{{- if and .Values.query.enabled .Values.query.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
{{- range .Values.global.imagePullSecrets }}
- name: {{ . }}
{{- end }}
metadata:
  name: {{ template "jaeger.query.serviceAccountName" . }}
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
    app.kubernetes.io/component: query
{{- end -}}
