apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aspen-mesh-metrics-collector-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: aspen-mesh-metrics-collector
    chart: {{ template "aspen-mesh-metrics-collector.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aspen-mesh-metrics-collector-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: aspen-mesh-metrics-collector
  namespace: {{ .Release.Namespace }}
