apiVersion: v1
kind: ConfigMap
metadata:
  name: aspen-mesh-analytics-manifest
  namespace: {{ .Release.Namespace }}
  labels:
    app: aspen-mesh-controlplane
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  features.yaml: |-
    ---
    metadata:
      name: admin
      kind: Admin
    spec:
      health:
        modelName: health_score_v1
        presentationName: health_score_v1
    ---
    metadata:
      name: health_score_v1
      kind: Presentation
    spec:
      modelReference:
        id: health_score_v1
        outputReferences:
        - name: health-score-result
          transformations:
          - name: no-transformation
            config:
            - "@type": "api.private.analytics.v1.manifest.transformations/transformations.Noop"
    ---
    metadata:
      name: health_score_v1
      kind: Model
    spec:
      id: health_score_v1
      inputs:
        dataReferences:
        - name: prometheus_health_score_info_namespaces
        - name: prometheus_health_score_info_workloads
        - name: prometheus_health_score_info_services
      configuration:
        weight4xx: "0.2"
        weight5xx: "0.4"
        weightLatency: "0.4"
        greenUpperThreshold: "1.0"
        greenToYellowThreshold: "0.9"
        yellowToRedThreshold: "0.75"
        redLowerThreshold: "0.0"
        latencyMaxRate: "1.0"
        latencyRateThreshold: "0.5"
        latencyMinRate: "0.0"
        yellow4xxMax: "1.0"
        greenToYellowThreshold4xx: "0.1"
        green4xxMin: "0.0"
        red5xxMax: "1.0"
        yellowToRedThreshold5xx: "0.05"
        greenToYellowThreshold5xx: "0.03"
        green5xxMin: "0.0"
        lowerLatencyThreshold: "0.331"
        upperLatencyThreshold: "0.692"
        maxLatency: "+Inf"
      outputs:
      - name: health-score-result-cluster
        prometheus:
          vector:
      - name: health-score-result-service
        prometheus:
          vector:
            labels:
              - namespace
              - service
      - name: health-score-result-namespace
        prometheus:
          vector:
            labels:
            - namespace
      - name: health-score-result-workload
        prometheus:
          vector:
            labels:
            - namespace
            - workload
    ---
    metadata:
      name: health_score_v2
      kind: Model
    spec:
      id: health_score_v2
      inputs:
        dataReferences:
        - name: prometheus_health_score_info_namespaces
        - name: prometheus_health_score_info_workloads
        - name: prometheus_health_score_info_services
      configuration:
        weight4xx: "0.85"
        weight5xx: "100.0"
        weightLatency: "1.5"
        target4xx: "0.00"
        target5xx: "0.00"
        targetLatency: "0.650"
      outputs:
      - name: health-score-result-cluster
        prometheus:
          vector:
      - name: health-score-result-service
        prometheus:
          vector:
            labels:
              - namespace
              - service
      - name: health-score-result-namespace
        prometheus:
          vector:
            labels:
            - namespace
      - name: health-score-result-workload
        prometheus:
          vector:
            labels:
            - namespace
            - workload
    ---
    metadata:
      name: prometheus_health_score_info_workloads
      kind: Data
    spec:
      sources:
      - prometheus:
          queries:
          - name: latencies
            queryReference:
              name: latencies
              parameters:
                GROUP: "destination_workload_namespace,destination_workload,le"
          - name: request-counts
            queryReference:
              name: request-counts
              parameters:
                GROUP: "destination_workload_namespace,destination_workload,response_code,connection_security_policy"
    ---
    metadata:
      name: prometheus_health_score_info_namespaces
      kind: Data
    spec:
      sources:
        - prometheus:
            queries:
              - name: latencies
                queryReference:
                  name: latencies
                  parameters:
                    GROUP: "destination_workload_namespace,le"
              - name: request-counts
                queryReference:
                  name: request-counts
                  parameters:
                    GROUP: "destination_workload_namespace,response_code,connection_security_policy"
    ---
    metadata:
      name: prometheus_health_score_info_services
      kind: Data
    spec:
      sources:
        - prometheus:
            queries:
              - name: latencies
                queryReference:
                  name: latencies
                  parameters:
                    GROUP: "destination_service_namespace,destination_service_name,le"
              - name: request-counts
                queryReference:
                  name: request-counts
                  parameters:
                    GROUP: "destination_service_namespace,destination_service_name,response_code,connection_security_policy"
    ---
    metadata:
      name: latencies
      kind: PrometheusQuery
    spec:
      query:
        queryString: sum(increase(istio_request_duration_seconds_bucket{LABELS}[STRIDE]))by(GROUP)
        parameters:
          LABELS: reporter="destination"
          STRIDE: 300s
          GROUP: ""
    ---
    metadata:
      name: request-counts
      kind: PrometheusQuery
    spec:
      query:
        queryString: sum(delta(istio_requests_total{LABELS}[STRIDE]))by(GROUP)
        parameters:
          LABELS: reporter="destination"
          STRIDE: 300s
          GROUP: ""
