apiVersion: policy.aspenmesh.io/v1alpha1
kind: Application
metadata:
  name: f5gc-webui
  namespace: f5gc
spec:
  inbound:
    ports:
      - number: 5000
        protocol: HTTP
        paths:
          - expose:
              public: true
              jwtSecured: false
            uri:
              prefix: /
---
apiVersion: policy.aspenmesh.io/v1alpha1
kind: SecureIngress
metadata:
  name: f5gcwebui
spec:
  domainName: "f5gc-webui.udf-demo.org"
  exposedApplications:
    - applicationReference:
        name: f5gc-webui
        namespace: f5gc
      serviceReference:
        name: f5gc-webui
        namespace: f5gc
---
apiVersion: policy.aspenmesh.io/v1alpha1
kind: SecureIngress
metadata:
  name: f5gcwebui1
spec:
  domainName: "10.1.1.5"
  exposedApplications:
    - applicationReference:
        name: f5gc-webui
        namespace: f5gc
      serviceReference:
        name: f5gc-webui
        namespace: f5gc
---
apiVersion: policy.aspenmesh.io/v1alpha1
kind: SecureIngress
metadata:
  name: f5gcwebui2
spec:
  domainName: "10.1.1.6"
  exposedApplications:
    - applicationReference:
        name: f5gc-webui
        namespace: f5gc
      serviceReference:
        name: f5gc-webui
        namespace: f5gc
---
apiVersion: policy.aspenmesh.io/v1alpha1
kind: SecureIngress
metadata:
  name: f5gcwebui3
spec:
  domainName: "10.1.1.7"
  exposedApplications:
    - applicationReference:
        name: f5gc-webui
        namespace: f5gc
      serviceReference:
        name: f5gc-webui
        namespace: f5gc
---
apiVersion: policy.aspenmesh.io/v1alpha1
kind: SecureIngress
metadata:
  name: f5gcwebui4
spec:
  domainName: "10.1.1.8"
  exposedApplications:
    - applicationReference:
        name: f5gc-webui
        namespace: f5gc
      serviceReference:
        name: f5gc-webui
        namespace: f5gc
---
apiVersion: policy.aspenmesh.io/v1alpha1
kind: SecureIngress
metadata:
  name: f5gcwebui5
spec:
  domainName: "10.1.1.9"
  exposedApplications:
    - applicationReference:
        name: f5gc-webui
        namespace: f5gc
      serviceReference:
        name: f5gc-webui
        namespace: f5gc
---
