apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: aspen-mesh-analysis-emulator
  namespace: {{ .Release.Namespace }}
  labels:
    app: aspen-mesh-analysis-emulator
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  host: aspen-mesh-analysis-emulator.{{ .Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
