all:
  hosts:
    master:
      ansible_host: 10.1.1.5
      ip: 10.1.1.5
      access_ip: 10.1.1.5
    node1:
      ansible_host: 10.1.1.6
      ip: 10.1.1.6
      access_ip: 10.1.1.6
    node2:
      ansible_host: 10.1.1.7
      ip: 10.1.1.7
      access_ip: 10.1.1.7
    node3:
      ansible_host: 10.1.1.8
      ip: 10.1.1.8
      access_ip: 10.1.1.8
    node4:
      ansible_host: 10.1.1.9
      ip: 10.1.1.9
      access_ip: 10.1.1.9
  children:
    kube-master:
      hosts:
        master:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
        node4:
    etcd:
      hosts:
        master:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
