---
apiVersion: v1
kind: ConfigMap
metadata:
  name: f5gc-pcf-config
data:
  pcfcfg.conf: |
    info:
      version: 1.0.0
      description: PCF initial local configuration
    
    configuration:
      pcfName: PCF # the name of this PCF
      sbi: # Service-based interface information
        scheme: http              # the protocol for sbi (http or https)
        registerIPv4: f5gc-pcf    # IP/DNS used to register to NRF
        bindingIPv4: 0.0.0.0      # IP used to bind the service
        port: 29507               # port used to bind the service
      timeFormat: 2019-01-02 15:04:05 # time format of this PCF
      defaultBdtRefId: BdtPolicyId-   # BDT Reference ID, indicating transfer policies of background data transfer
      nrfUri: http://f5gc-nrf:29510   # a valid URI of NRF
      serviceList:   # the SBI services provided by this PCF, refer to TS 29.507
        - serviceName: npcf-am-policy-control   # Npcf_AMPolicyControl service
        - serviceName: npcf-smpolicycontrol     # Npcf_SMPolicyControl service
          suppFeat: 3fff # the features supported by Npcf_SMPolicyControl, name defined in TS 29.512 5.8-1, value defined in TS 29.571 5.2.2
        - serviceName: npcf-bdtpolicycontrol    # Npcf_BDTPolicyControl service
        - serviceName: npcf-policyauthorization # Npcf_PolicyAuthorization service
          suppFeat: 3    # the features supported by Npcf_PolicyAuthorization, name defined in TS 29.514 5.8-1, value defined in TS 29.571 5.2.2
        - serviceName: npcf-eventexposure       # Npcf_EventExposure service
        - serviceName: npcf-ue-policy-control   # Npcf_UEPolicyControl service
      mongodb:       # the mongodb connected by this PCF
        name: free5gc                       # name of the mongodb
        url: mongodb://f5gc-mongodb:27017   # a valid URL of the mongodb

    # the kind of log output
      # debugLevel: trace, debug, info, warn, error, fatal, panic
      # ReportCaller: true or false
    logger:
      PCF:
        debugLevel: trace
        ReportCaller: true
      PathUtil:
        debugLevel: info
        ReportCaller: false
      OpenApi:
        debugLevel: debug
        ReportCaller: true
