resources:
  - 00_pcf-sa.yaml
  - 01_pcf-rbac.yaml
  - 02_pcf-configmap.yaml
  - 03_pcf-service.yaml
  - 04_pcf-deployment.yaml

namespace: f5gc

secretGenerator:
- name: f5gc-pcf-tls-secret
  namespace: f5gc
  files:
  - cert/pcf.pem
  - cert/pcf.key
  type: "Opaque"
generatorOptions:
  disableNameSuffixHash: true
